language: java
  sudo: false
  env:
    global:
    - CODECOV_TOKEN="ce7505ac-7ee4-474c-ad0c-b32b987592cf"
  script: "mvn cobertura:cobertura"
#  # safelist
#  branches:
#    only:
#    - master
  after_success:
  - bash <(curl -s https://codecov.io/bash)
  notifications:
    emails:
      recipients:
      - eng.paulovieiraa@gmail.com
      on_success: always
      on_failure: always